import React, { useState } from 'react';

const Contact = () => {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });
    const [showModal, setShowModal] = useState(false);

      const handleSubmit = (e) => {
          e.preventDefault();
              setShowModal(true);
                };

                  const handleChange = (e) => {
                      setFormData({ ...formData, [e.target.name]: e.target.value });
                        };

                          return (
                              <div style={{ padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
                                    <h1 style={{ textAlign: 'center' }}>Contact Us</h1>
                                          
                                                <form onSubmit={handleSubmit} style={formStyle}>
                                                        <input
                                                                  type="text"
                                                                            name="name"
                                                                                      placeholder="Your Name"
                                                                                                value={formData.name}
                                                                                                          onChange={handleChange}
                                                                                                                    style={inputStyle}
                                                                                                                              required
                                                                                                                                      />
                                                                                                                                              <input
                                                                                                                                                        type="email"
                                                                                                                                                                  name="email"
                                                                                                                                                                            placeholder="Your Email"
                                                                                                                                                                                      value={formData.email}
                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                          style={inputStyle}
                                                                                                                                                                                                                    required
                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                    <textarea
                                                                                                                                                                                                                                              name="message"
                                                                                                                                                                                                                                                        placeholder="Your Message"
                                                                                                                                                                                                                                                                  value={formData.message}
                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                      style={{...inputStyle, height: '150px'}}
                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                <button type="submit" style={submitButtonStyle}>
                                                                                                                                                                                                                                                                                                                          Send Message
                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                              {/* Modal */}
                                                                                                                                                                                                                                                                                                                                                    {showModal && (
                                                                                                                                                                                                                                                                                                                                                            <div style={modalOverlayStyle}>
                                                                                                                                                                                                                                                                                                                                                                      <div style={modalStyle}>
                                                                                                                                                                                                                                                                                                                                                                                  <h3>✅ Form Submitted Successfully!</h3>
                                                                                                                                                                                                                                                                                                                                                                                              <p>Thank you {formData.name}, we'll contact you at {formData.email}</p>
                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setShowModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                      style={closeButtonStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Close
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const formStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              flexDirection: 'column',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gap: '1rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: '2rem'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: '2px solid #ddd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: '8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: '1rem'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const submitButtonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '15px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: '#667eea',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: '1.1rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: 'pointer'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const modalOverlayStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position: 'fixed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                right: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bottom: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: 'rgba(0,0,0,0.5)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          justifyContent: 'center'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const modalStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxWidth: '400px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const closeButtonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: '10px 20px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#667eea',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: '5px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: '1rem'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Contact;