import React from 'react';
import { Link } from 'react-router-dom';

const Home = () => {
  return (
      <div style={containerStyle}>
            {/* Hero Section */}
                  <div style={heroStyle}>
                          <h1 style={titleStyle}>Welcome to MovieMagic 🎬</h1>
                                  <p style={subtitleStyle}>
                                            Discover, Explore, and Enjoy the World of Cinema
                                                    </p>
                                                            <Link to="/movies" style={ctaButtonStyle}>
                                                                      Explore Movies
                                                                              </Link>
                                                                                    </div>

                                                                                          {/* Features Section */}
                                                                                                <div style={featuresContainer}>
                                                                                                        <h2 style={sectionTitle}>Why Choose MovieMagic?</h2>
                                                                                                                <div style={featuresGrid}>
                                                                                                                          <div style={featureCard}>
                                                                                                                                      <div style={iconStyle}>🎭</div>
                                                                                                                                                  <h3>Vast Collection</h3>
                                                                                                                                                              <p>Browse through thousands of movies from various genres and eras</p>
                                                                                                                                                                        </div>

                                                                                                                                                                                  <div style={featureCard}>
                                                                                                                                                                                              <div style={iconStyle}>⭐</div>
                                                                                                                                                                                                          <h3>Ratings & Reviews</h3>
                                                                                                                                                                                                                      <p>See what critics and audiences are saying about your favorite films</p>
                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                          <div style={featureCard}>
                                                                                                                                                                                                                                                      <div style={iconStyle}>🎟️</div>
                                                                                                                                                                                                                                                                  <h3>Latest Updates</h3>
                                                                                                                                                                                                                                                                              <p>Stay updated with new releases and upcoming blockbusters</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                            {/* Quick Stats */}
                                                                                                                                                                                                                                                                                                                  <div style={statsContainer}>
                                                                                                                                                                                                                                                                                                                          <div style={statItem}>
                                                                                                                                                                                                                                                                                                                                    <h3>10,000+</h3>
                                                                                                                                                                                                                                                                                                                                              <p>Movies</p>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                              <div style={statItem}>
                                                                                                                                                                                                                                                                                                                                                                        <h3>50+</h3>
                                                                                                                                                                                                                                                                                                                                                                                  <p>Genres</p>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <div style={statItem}>
                                                                                                                                                                                                                                                                                                                                                                                                            <h3>100+</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Countries</p>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                          // Styles
                                                                                                                                                                                                                                                                                                                                                                                                                                          const containerStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                            minHeight: '100vh',
                                                                                                                                                                                                                                                                                                                                                                                                                                              background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                const heroStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '100px 2rem 80px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: 'rgba(0, 0, 0, 0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                      const titleStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: '3.5rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: '1rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                              textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                              const subtitleStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: '1.3rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: '2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opacity: '0.9',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ctaButtonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: 'inline-block',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: '15px 30px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#ff6b6b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textDecoration: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: '50px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '1.1rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: 'all 0.3s ease',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        boxShadow: '0 4px 15px rgba(255, 107, 107, 0.4)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const featuresContainer = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: '80px 2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const sectionTitle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '2.5rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: '3rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#2c3e50',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const featuresGrid = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: 'grid',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: '2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              maxWidth: '1200px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin: '0 auto',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const featureCard = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: '15px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#f8f9fa',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          boxShadow: '0 5px 15px rgba(0,0,0,0.1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition: 'transform 0.3s ease',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const iconStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: '3rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: '1rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const statsContainer = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gap: '4rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: '60px 2rem',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#2c3e50',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const statItem = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Add hover effects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styleSheet = document.styleSheets[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              styleSheet.insertRule(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .cta-button:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transform: translateY(-3px);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        box-shadow: 0 8px 25px rgba(255, 107, 107, 0.6);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `, styleSheet.cssRules.length);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          styleSheet.insertRule(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .feature-card:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transform: translateY(-5px);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `, styleSheet.cssRules.length);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Home;